name: OPA Test Suite

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Build OPA Docker image
        id: build-opa-image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: false
          tags: opa-test-image:latest

      - name: Run OPA test suite
        id: run-opa-test
        run: |
          docker pull openpolicyagent/opa
          docker run --rm -v $(pwd)/opa-test-data:/opa-test-data openpolicyagent/opa:latest opa test opa-test-data

      - name: Check test results
        id: check-test-results
        run: |
          if [ ! -f opa-test-data/test-results.json ]; then
            echo "Test results file not found"
            exit 1
          fi

          if grep -q 'FAILURE' opa-test-data/test-results.json; then
            echo "Test failures detected"
            exit 1
          fi

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: opa-test-results
          path: opa-test-data/test-results.json